# The PublicBodyCategories structure works like this:
# [
#   "Main category name",
#       [ "tag_to_use_as_category", "Sub category title", "sentence that can describes things in this subcategory" ],
#       [ "another_tag", "Second sub category title", "another descriptive sentence for things in this subcategory"],
#   "Another main category name",
#       [ "another_tag_2", "Another sub category title", "another descriptive sentence"]
# ])

PublicBodyCategories.add(:en, [
    "Federal Portfolios",
        [ "attorney-general","Attorney-General","part of the Attorney-General portfolio" ],
        [ "agriculture_fisheries_and_forestry","Agriculture, Fisheries and Forestry","part of the Agriculture, Fisheries and Forestry portfolio" ],
        [ "broadband_communications_and_the_digital_economy","Broadband, Communications and the Digital Economy","part of the Broadband, Communications and the Digital Economy portfolio" ],
        [ "climate_change_and_energy_efficiency","Climate Change and Energy Efficiency","part of the Climate Change and Energy Efficiency portfolio" ],
        [ "defence","Defence","part of the Defence portfolio" ],
        [ "education_employment_and_workplace_relations","Education, Employment and Workplace Relations","part of the Education, Employment and Workplace Relations portfolio" ],
        [ "families_housing_community_services_and_indigenous_affairs","Families, Housing, Community Services and Indigenous Affairs","part of the Families, Housing, Community Services and Indigenous Affairs portfolio" ],
        [ "finance_and_deregulation","Finance and Deregulation","part of the Finance and Deregulation portfolio" ],
        [ "foreign_affairs_and_trade","Foreign Affairs and Trade","part of the Foreign Affairs and Trade portfolio" ],
        [ "health_and_ageing","Health and Ageing","part of the Health and Ageing portfolio" ],
        [ "human_services","Human Services","part of the Human Services portfolio" ],
        [ "immigration_&_citizenship","Immigration & Citizenship","part of the Immigration & Citizenship portfolio" ],
        [ "industry_innovation_science_research_and_tertiary_education","Industry, Innovation, Science, Research and Tertiary Education","part of the Industry, Innovation, Science, Research and Tertiary Education portfolio" ],
        [ "infrastructure_and_transport","Infrastructure and Transport","part of the Infrastructure and Transport portfolio" ],
        [ "regional_australia_local_government_arts_and_sport","Regional Australia, Local Government, Arts and Sport","part of the Regional Australia, Local Government, Arts and Sport portfolio" ],
        [ "resources_energy_and_tourism","Resources Energy and Tourism","part of the Resources Energy and Tourism portfolio" ],
        [ "sustainability_environment_water_population_and_communities","Sustainability, Environment, Water, Population and Communities","part of the Sustainability, Environment, Water, Population and Communities portfolio" ],
        [ "prime_minister_and_cabinet","Prime Minister and Cabinet","part of the Prime Minister and Cabinet portfolio" ],
        [ "treasury","Treasury","part of the Treasury portfolio" ],
        [ "veterans_affairs","Veterans' Affairs","part of the Veterans' Affairs portfolio" ],
    "Ministers and Assistant Ministers",
        [ "federal-ministers","Federal Ministers","a minister in the Federal Government" ],
        [ "act-ministers","ACT Ministers","a minister in the ACT State Government" ],
        [ "nsw-ministers","NSW Government","a minister in the NSW State Government" ],
        [ "nt-ministers","NT Government","a minister in the NT State Government" ],
        [ "qld-ministers","QLD Government","a minister in the QLD State Government" ],
        [ "sa-ministers","SA Government","a minister in the SA State Government" ],
        [ "tas-ministers","TAS Government","a minister in the TAS State Government" ],
        [ "vic-ministers","VIC Government","a minister in the VIC State Government" ],
        [ "wa-ministers","WA Government","a minister in the WA State Government" ],
    "State Governments",
        [ "act-government","ACT Government","part of the ACT State Government" ],
        [ "nsw-government","NSW Government","part of the NSW State Government" ],
        [ "nt-government","NT Government","part of the NT State Government" ],
        [ "qld-government","QLD Government","part of the QLD State Government" ],
        [ "sa-government","SA Government","part of the SA State Government" ],
        [ "tas-government","TAS Government","part of the TAS State Government" ],
        [ "vic-government","VIC Government","part of the VIC State Government" ],
        [ "wa-government","WA Government","part of the WA State Government" ],
    "Local Government",
        [ "act-local","ACT Local Government","an ACT Local Government" ],
        [ "nsw-local","NSW Local Government","a NSW Local Government" ],
        [ "nt-Local","NT Local Government","a NT Local Government" ],
        [ "qld-local","QLD Local Government","a QLD Local Government" ],
        [ "sa-local","SA Local Government","a SA Local Government" ],
        [ "tas-local","TAS Local Government","a TAS Local Government" ],
        [ "vic-local","VIC Local Government","a VIC Local Government" ],
        [ "wa-local","WA Local Government","a WA Local Government" ],


])
